//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Code/Scripts/Input/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Movements"",
            ""id"": ""8a5de89f-26df-4d1c-9de6-b68b00b37651"",
            ""actions"": [
                {
                    ""name"": ""RotateTargeting"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9e5d5f1a-2424-4771-9c0b-2bc44a2716e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c01bdddf-b8b6-4b6d-81c5-3de488c7719d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""29307a9d-64d2-4dd9-bfd4-4a273a8d7dc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""fc9590ec-2179-4c6a-90c0-99686d63b937"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""b6c36158-0b69-4000-a23c-8b0f84c9d269"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleCamera"",
                    ""type"": ""Button"",
                    ""id"": ""a8c27168-0582-48d7-9884-d6aad29cdcfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryL"",
                    ""type"": ""Button"",
                    ""id"": ""f1489da5-52d3-4682-b637-7b3e1dce2818"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryR"",
                    ""type"": ""Button"",
                    ""id"": ""bfcf4968-b5db-4391-a065-f507825a19db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action1"",
                    ""type"": ""Button"",
                    ""id"": ""cc756a6c-6ee7-41e9-9916-59e74490f924"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action2"",
                    ""type"": ""Button"",
                    ""id"": ""01bd678b-7768-4193-94de-e9efce07afd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action3"",
                    ""type"": ""Button"",
                    ""id"": ""c8eccd42-6920-455e-bc8d-db7332a2822a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""b70a1993-1257-4031-9daa-0c05d59a9c70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ffba2592-9679-4cb2-a756-35d1477f4c97"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Golf;Key"",
                    ""action"": ""RotateTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyb"",
                    ""id"": ""e2e06c81-8767-455b-a876-3cfdb446864a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateTargeting"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""34f30b22-3a0a-4773-b266-74f7c876dfa7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6332b52a-5c93-44f1-8f9a-e855f9168690"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""974fac3e-18b5-4758-afb8-95488aa22095"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""25fc3e55-a74c-4cfc-9bcc-bea821007959"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateTargeting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a34cb472-0182-4e61-89aa-4595f54e42b4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Golf;Key"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyb"",
                    ""id"": ""9a57458c-a4e1-4803-bb90-29e9d512dcab"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""386b3154-3394-47c0-af3e-b45e985c746e"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""540d9487-134f-410d-8dd8-bb92309ba83f"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ea1931fd-c34e-4c0b-8823-d9743ee15b15"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""baa97b46-6536-4c3c-8330-220ef035dea8"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""77e7f788-4a38-4e7f-b55d-e4747cc66d97"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef9508eb-2ca1-47e4-90c6-0dd7cfcabab0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6292f2d0-cc89-47ce-8a19-8e0634d28276"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45a65ba9-6a97-46ee-98fd-e96d38b1b809"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bab4b51-7013-4419-b34b-799f585946fd"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e155307-b76c-4a4c-80d5-cdc271298ec2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4232614-64de-40de-8988-20c7f84ec7f0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0bceeeb-dbea-4038-a695-121099e4d41f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CycleCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""509f5e39-854f-4894-b2ab-17d1e0fc0807"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e09f611a-2783-4629-946c-2c87b9019fd2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6b5b1d7-87b4-40ed-9b95-4d8e5fa03375"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0896c4ae-2697-47d4-9af6-89eef83528b4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b222375-3f53-4faf-afb8-fb4b03d2b9e8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d67f8806-eff8-43b6-8cfa-9db8a93ba30f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a3eea6-5519-45bb-9d35-3340cee63647"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2e0fc66-02b5-4c19-88d7-ad26175c7106"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ee64c6b-a36b-457f-93ad-8a457a9bd4ff"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Golf"",
            ""bindingGroup"": ""Golf"",
            ""devices"": []
        },
        {
            ""name"": ""Key"",
            ""bindingGroup"": ""Key"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Movements
        m_Movements = asset.FindActionMap("Movements", throwIfNotFound: true);
        m_Movements_RotateTargeting = m_Movements.FindAction("RotateTargeting", throwIfNotFound: true);
        m_Movements_RotateCamera = m_Movements.FindAction("RotateCamera", throwIfNotFound: true);
        m_Movements_Shoot = m_Movements.FindAction("Shoot", throwIfNotFound: true);
        m_Movements_LShoulder = m_Movements.FindAction("LShoulder", throwIfNotFound: true);
        m_Movements_RShoulder = m_Movements.FindAction("RShoulder", throwIfNotFound: true);
        m_Movements_CycleCamera = m_Movements.FindAction("CycleCamera", throwIfNotFound: true);
        m_Movements_InventoryL = m_Movements.FindAction("InventoryL", throwIfNotFound: true);
        m_Movements_InventoryR = m_Movements.FindAction("InventoryR", throwIfNotFound: true);
        m_Movements_Action1 = m_Movements.FindAction("Action1", throwIfNotFound: true);
        m_Movements_Action2 = m_Movements.FindAction("Action2", throwIfNotFound: true);
        m_Movements_Action3 = m_Movements.FindAction("Action3", throwIfNotFound: true);
        m_Movements_Cancel = m_Movements.FindAction("Cancel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movements
    private readonly InputActionMap m_Movements;
    private List<IMovementsActions> m_MovementsActionsCallbackInterfaces = new List<IMovementsActions>();
    private readonly InputAction m_Movements_RotateTargeting;
    private readonly InputAction m_Movements_RotateCamera;
    private readonly InputAction m_Movements_Shoot;
    private readonly InputAction m_Movements_LShoulder;
    private readonly InputAction m_Movements_RShoulder;
    private readonly InputAction m_Movements_CycleCamera;
    private readonly InputAction m_Movements_InventoryL;
    private readonly InputAction m_Movements_InventoryR;
    private readonly InputAction m_Movements_Action1;
    private readonly InputAction m_Movements_Action2;
    private readonly InputAction m_Movements_Action3;
    private readonly InputAction m_Movements_Cancel;
    public struct MovementsActions
    {
        private @Inputs m_Wrapper;
        public MovementsActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @RotateTargeting => m_Wrapper.m_Movements_RotateTargeting;
        public InputAction @RotateCamera => m_Wrapper.m_Movements_RotateCamera;
        public InputAction @Shoot => m_Wrapper.m_Movements_Shoot;
        public InputAction @LShoulder => m_Wrapper.m_Movements_LShoulder;
        public InputAction @RShoulder => m_Wrapper.m_Movements_RShoulder;
        public InputAction @CycleCamera => m_Wrapper.m_Movements_CycleCamera;
        public InputAction @InventoryL => m_Wrapper.m_Movements_InventoryL;
        public InputAction @InventoryR => m_Wrapper.m_Movements_InventoryR;
        public InputAction @Action1 => m_Wrapper.m_Movements_Action1;
        public InputAction @Action2 => m_Wrapper.m_Movements_Action2;
        public InputAction @Action3 => m_Wrapper.m_Movements_Action3;
        public InputAction @Cancel => m_Wrapper.m_Movements_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_Movements; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementsActions set) { return set.Get(); }
        public void AddCallbacks(IMovementsActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementsActionsCallbackInterfaces.Add(instance);
            @RotateTargeting.started += instance.OnRotateTargeting;
            @RotateTargeting.performed += instance.OnRotateTargeting;
            @RotateTargeting.canceled += instance.OnRotateTargeting;
            @RotateCamera.started += instance.OnRotateCamera;
            @RotateCamera.performed += instance.OnRotateCamera;
            @RotateCamera.canceled += instance.OnRotateCamera;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @LShoulder.started += instance.OnLShoulder;
            @LShoulder.performed += instance.OnLShoulder;
            @LShoulder.canceled += instance.OnLShoulder;
            @RShoulder.started += instance.OnRShoulder;
            @RShoulder.performed += instance.OnRShoulder;
            @RShoulder.canceled += instance.OnRShoulder;
            @CycleCamera.started += instance.OnCycleCamera;
            @CycleCamera.performed += instance.OnCycleCamera;
            @CycleCamera.canceled += instance.OnCycleCamera;
            @InventoryL.started += instance.OnInventoryL;
            @InventoryL.performed += instance.OnInventoryL;
            @InventoryL.canceled += instance.OnInventoryL;
            @InventoryR.started += instance.OnInventoryR;
            @InventoryR.performed += instance.OnInventoryR;
            @InventoryR.canceled += instance.OnInventoryR;
            @Action1.started += instance.OnAction1;
            @Action1.performed += instance.OnAction1;
            @Action1.canceled += instance.OnAction1;
            @Action2.started += instance.OnAction2;
            @Action2.performed += instance.OnAction2;
            @Action2.canceled += instance.OnAction2;
            @Action3.started += instance.OnAction3;
            @Action3.performed += instance.OnAction3;
            @Action3.canceled += instance.OnAction3;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
        }

        private void UnregisterCallbacks(IMovementsActions instance)
        {
            @RotateTargeting.started -= instance.OnRotateTargeting;
            @RotateTargeting.performed -= instance.OnRotateTargeting;
            @RotateTargeting.canceled -= instance.OnRotateTargeting;
            @RotateCamera.started -= instance.OnRotateCamera;
            @RotateCamera.performed -= instance.OnRotateCamera;
            @RotateCamera.canceled -= instance.OnRotateCamera;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @LShoulder.started -= instance.OnLShoulder;
            @LShoulder.performed -= instance.OnLShoulder;
            @LShoulder.canceled -= instance.OnLShoulder;
            @RShoulder.started -= instance.OnRShoulder;
            @RShoulder.performed -= instance.OnRShoulder;
            @RShoulder.canceled -= instance.OnRShoulder;
            @CycleCamera.started -= instance.OnCycleCamera;
            @CycleCamera.performed -= instance.OnCycleCamera;
            @CycleCamera.canceled -= instance.OnCycleCamera;
            @InventoryL.started -= instance.OnInventoryL;
            @InventoryL.performed -= instance.OnInventoryL;
            @InventoryL.canceled -= instance.OnInventoryL;
            @InventoryR.started -= instance.OnInventoryR;
            @InventoryR.performed -= instance.OnInventoryR;
            @InventoryR.canceled -= instance.OnInventoryR;
            @Action1.started -= instance.OnAction1;
            @Action1.performed -= instance.OnAction1;
            @Action1.canceled -= instance.OnAction1;
            @Action2.started -= instance.OnAction2;
            @Action2.performed -= instance.OnAction2;
            @Action2.canceled -= instance.OnAction2;
            @Action3.started -= instance.OnAction3;
            @Action3.performed -= instance.OnAction3;
            @Action3.canceled -= instance.OnAction3;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
        }

        public void RemoveCallbacks(IMovementsActions instance)
        {
            if (m_Wrapper.m_MovementsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementsActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementsActions @Movements => new MovementsActions(this);
    private int m_GolfSchemeIndex = -1;
    public InputControlScheme GolfScheme
    {
        get
        {
            if (m_GolfSchemeIndex == -1) m_GolfSchemeIndex = asset.FindControlSchemeIndex("Golf");
            return asset.controlSchemes[m_GolfSchemeIndex];
        }
    }
    private int m_KeySchemeIndex = -1;
    public InputControlScheme KeyScheme
    {
        get
        {
            if (m_KeySchemeIndex == -1) m_KeySchemeIndex = asset.FindControlSchemeIndex("Key");
            return asset.controlSchemes[m_KeySchemeIndex];
        }
    }
    public interface IMovementsActions
    {
        void OnRotateTargeting(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnLShoulder(InputAction.CallbackContext context);
        void OnRShoulder(InputAction.CallbackContext context);
        void OnCycleCamera(InputAction.CallbackContext context);
        void OnInventoryL(InputAction.CallbackContext context);
        void OnInventoryR(InputAction.CallbackContext context);
        void OnAction1(InputAction.CallbackContext context);
        void OnAction2(InputAction.CallbackContext context);
        void OnAction3(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
}
